defaults:
  - env: microgrid
  - _self_

ENV_NAME: ${env.ENV_NAME}

ALG: "STAS-MAPPO-IA-CTDE-24h-FullGlobalReturn"
LR: 3e-4
NUM_ENVS: 4
NUM_STEPS: 24
TOTAL_TIMESTEPS: 960000
UPDATE_EPOCHS: 8
NUM_MINIBATCHES: 1
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
ENT_COEF: 0.01
VF_COEF: 1.0
MAX_GRAD_NORM: 5
ACTIVATION: "tanh"
ANNEAL_LR: False
LOG_STD_INIT: -1.0

SEED: 30
NUM_SEEDS: 1

ACTOR_LAYERS: [128, 128]
CRITIC_LAYERS: [128, 128]

STAS:
  MODE: "legacy"
  MIX_COEF: 1.0
  LR: 1e-3
  EMB_DIM: 128
  N_HEADS: 4
  N_LAYERS: 2
  SAMPLE_NUM: 4
  EVAL_MASK_SEED: 3030
  EVAL_MASK_COUNT: 8
  DIAGNOSTICS_PATH: null
  DROPOUT: 0.1
  BUFFER_SIZE: 128
  BATCH_SIZE: 16
  UPDATE_FREQ: 1
  UPDATES_PER_STEP: 1
  WARMUP_ROLLOUTS: 2
  GLOBAL_REWARD_AGG: "sum"
  CUDA: False
  DEVICE: "cpu"

ENTITY: null
PROJECT: "hypermarl-microgrid"
WANDB_MODE: "disabled"
EXP_NAME: ${hydra:runtime.config_name}
EXP_TAGS: ["${ALG}", "FF", "MAPPO", "STAS", "IndependentActors", "${ENV_NAME}"]
RUN_NAME: "${ENV_NAME}__${EXP_NAME}__${SEED}__${now:%Y-%m-%d_%H-%M-%S}"
GROUP: "${ENV_NAME}_${EXP_NAME}"

EVAL_INTERVAL: 100000000
EVAL_EPISODES: 2
EVAL_DETERMINISTIC: True
EVAL_PARALLEL: False

TEST_ENV_KWARGS: {}
TRAIN_ENV_KWARGS:
  auto_reset: True
ACTION_SPACE_TYPE: "continuous"

CAPTURE_VIDEO_INTERVAL: null
CHECKPOINT_INTERVAL: 96000
CHECKPOINT: True
HANDLE_TERMINAL_OBS: True
CALCULATE_TEAM_DIVERSITY_METRICS: False
LOG_INTERVAL: 100

MICROGRID_CONFIG_OVERRIDES: null
