defaults:
  - env: microgrid
  - _self_

ENV_NAME: ${env.ENV_NAME}

ALG: "Hypermarl(IPPO)"
LR: 0.00005
NUM_ENVS: 4
NUM_STEPS: 24
TOTAL_TIMESTEPS: 960
UPDATE_EPOCHS: 2
NUM_MINIBATCHES: 1
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
ENT_COEF: 0.01
VF_COEF: 1.0
MAX_GRAD_NORM: 5
ACTIVATION: "tanh"
ANNEAL_LR: False
LOG_STD_INIT: -1.0

HYPERNET_EMBEDDING_DIM: null
USE_AGENT_ID_EMBEDDINGS: False
USE_BIAS_IN_HYPERNET: True
HYPERNET_HIDDEN_DIMS: [64]
SAVE_EMBEDDINGS_INTERVAL: 100000000

SEED: 30
NUM_SEEDS: 1

ACTOR_LAYERS: [64, 64]
CRITIC_LAYERS: [64, 64]

ENTITY: null
PROJECT: "hypermarl-microgrid"
WANDB_MODE: "disabled"
EXP_NAME: ${hydra:runtime.config_name}
EXP_TAGS: ["${ALG}", "FF", "Hypernets", "${ENV_NAME}", "smoke"]
RUN_NAME: "${ENV_NAME}__${EXP_NAME}__${SEED}__${now:%Y-%m-%d_%H-%M-%S}"
GROUP: "${ENV_NAME}_${EXP_NAME}"

EVAL_INTERVAL: 100000000
EVAL_EPISODES: 2
EVAL_DETERMINISTIC: True
EVAL_PARALLEL: False

env:
  ENV_KWARGS:
    one_hot_encode_agent_id: True

TEST_ENV_KWARGS: {}
TRAIN_ENV_KWARGS:
  auto_reset: True
ACTION_SPACE_TYPE: "continuous"

CAPTURE_VIDEO_INTERVAL: null
CHECKPOINT_INTERVAL: 100000000
CHECKPOINT: False
HANDLE_TERMINAL_OBS: True
CALCULATE_TEAM_DIVERSITY_METRICS: False
